name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Ensure the workflow has permission to write packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v1
        with: 
          path: ${{ github.workspace }}/cache
          key: ${{ runner.os }}-docker-${{ hashfiles('cache/**') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build the Docker image
        run: |
          docker buildx build \
          --cache-from "type=local,src=$GITHUB_WORKSPACE/cache"
          --cache-to "type=local,dest=$GITHUB_WORKSPACE/cache"
          --output "type=image, name=ghcr.io/${{ github.repository }}:latest,push=false"

      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
